package at.redeye.SqlDBInterface.SqlDBIO.impl;

public enum DBDataType {
	
	DB_TYPE_STRING,
	DB_TYPE_LONG,
	DB_TYPE_FLOAT,
	DB_TYPE_DOUBLE,
	DB_TYPE_INTEGER,
	DB_TYPE_BOOLEAN,
	DB_TYPE_BIT,
	DB_TYPE_SHORT,
	DB_TYPE_DATE,
	DB_TYPE_TIME,
	DB_TYPE_DATETIME,
    DB_TYPE_BLOB

}
