/*
 * testFrame.java
 *
 * Created on 3. Januar 2009, 09:39
 */

package at.redeye.FrameWork.widgets.calendarday;

/**
 *
 * @author  martin
 */
public class testFrame extends javax.swing.JFrame implements DayEventListener {

    CalendarDay day1 = new CalendarDay();
    boolean setActive = true;

    /** Creates new form testFrame */
    public testFrame() {
        initComponents();

        setContentPane(day1);

        day1.setInactive();
        day1.clear();
        day1.setListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> new testFrame().setVisible(true));
    }

    @Override
    public void onClicked(CalendarDay day) {
        if(setActive)
        {
            day.setSelected();
        }
        else
        {
            day.setUnSelected();
        }

        setActive = !setActive;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
