name: Release Java Application

on:
  push:
    tags:
      - 'msgviewer-*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./MSGViewer/target/msgviewer.jar
